openapi: 3.0.0
info:
  title: MLink con Swagger
  version: 1.0.0
  description: Documentación de la API Rest "MLink" usando Swagger
  contact:
    name: Rafael Alday
    url: https://alday.dev
    email: aldaydev@gmail.com

servers:
  - url: https://devtree-server-nwgs.onrender.com
    description: Production server
  - url: http://localhost:4000
    description: Servidor local
  

paths: {}       # Lo dejamos vacío, se combina con los paths externos
components:
  schemas: {}       # Igual, vacío y lo cargamos desde components/schemas.yaml
  responses: {}
  parameters: {}