openapi: 3.0.0
info:
  title: MLink con Swagger
  version: 1.0.0
  description: Documentación de la API Rest "MLink" usando Swagger

servers:
  - url: http://localhost:4000
    description: Servidor local
  - url: https://devtree-server-nwgs.onrender.com
    description: Production server

paths: {}       # Lo dejamos vacío, se combina con los paths externos
components:
  schemas: {}       # Igual, vacío y lo cargamos desde components/schemas.yaml
  responses: {}
  parameters: {}